#!/usr/bin/env node
// Translate template.html → template-en.html + template-th.html
// Run: node translate.mjs

import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const src = readFileSync(join(__dirname, 'template.html'), 'utf8')

// ── DICTIONARIES (order matters — longer phrases first) ──
const dict = {
  en: [
    // HTML attrs
    ['<html lang="he" dir="rtl">', '<html lang="en" dir="ltr">'],
    ['direction: rtl;', 'direction: ltr;'],
    ['margin-left: 10px', 'margin-right: 10px'],
    ['.roi-savings-value', '.roi-savings-value'],
    // Title/meta
    ['TM Energy — הצעת מחיר סולארית · אמיר מזרחי', 'TM Energy — Solar Proposal · Amir Mizrahi'],
    ['הצעת מחיר למערכת סולארית', 'Solar system proposal'],
    ['הצעת מחיר', 'Proposal'],
    ['קופנגן, תאילנד', 'Koh Phangan, Thailand'],
    // Nav
    ['TM ENERGY · PHANGAN', 'TM ENERGY · PHANGAN'],
    ['REF · AMIR-001 · 2026', 'REF · AMIR-001 · 2026'],
    // Hero
    ['הצעת מחיר · אפריל 2026', 'Proposal · April 2026'],
    ['מערכת סולארית', 'Solar System'],
    ['12.76 kWp + סוללה', '12.76 kWp + Battery'],
    ['מערכת היברידית מלאה Huawei לקופנגן — 22 פאנלים Jinko N-Type + אינוורטר Huawei SUN2000 + סוללת Huawei LUNA2000 10 kWh. עצמאות אנרגטית גם בהפסקות חשמל, חיסכון של 79,900 ฿ בשנה.', 'Complete hybrid Huawei system for Koh Phangan — 22× Jinko N-Type panels + Huawei SUN2000 inverter + Huawei LUNA2000 10 kWh battery. Energy independence even during blackouts, ฿79,900 annual savings.'],
    ['לקוח', 'Client'],
    ['אמיר מזרחי', 'Amir Mizrahi'],
    ['מיקום', 'Location'],
    ['Koh Phangan, TH', 'Koh Phangan, TH'],
    ['תוקף', 'Valid for'],
    ['30 יום', '30 days'],
    // Visual section
    ['סימולציה ויזואלית', 'Visual Simulation'],
    ['איך המערכת תיראה על הגג שלך', 'How the system will look on your roof'],
    ['דימוי AI מדויק המבוסס על תמונת הרחפן של הגג — מראה מדויק של מיקום ומספר הפאנלים.', 'AI-accurate render based on the drone image of your roof — exact panel placement and count.'],
    ['גג מקורי', 'Original roof'],
    ['גג עם פאנלים', 'Roof with panels'],
    ['לפני', 'Before'],
    ['אחרי', 'After'],
    ['תמונת רחפן', 'Drone photo'],
    ['22 פאנלים · 12.76 kWp', '22 panels · 12.76 kWp'],
    // Roof analysis
    ['ניתוח הגג', 'Roof Analysis'],
    ['מדידות ותכנון', 'Measurements & Planning'],
    ['m² שטח גג', 'm² roof area'],
    ['פאנלים פעילים', 'Active panels'],
    ['אוריינטציה', 'Orientation'],
    ['ציר N-S', 'N-S axis'],
    ['סוג גג', 'Roof type'],
    ['רעפים', 'Ceramic tiles'],
    ['מדרון שמאל (מזרח)', 'Left slope (East)'],
    ['מדרון ימין (מערב)', 'Right slope (West)'],
    ['חלק עליון (clerestory)', 'Upper section (clerestory)'],
    ['סה״כ פאנלים', 'Total panels'],
    ['הצללה צפויה', 'Expected shading'],
    ['פאנלים (2×5)', 'panels (2×5)'],
    ['פאנלים (2×4)', 'panels (2×4)'],
    ['פאנלים נוספים (2×2)', 'additional panels (2×2)'],
    ['5-8% בבוקר מעץ המנגו · זניח', '5-8% morning from mango tree · negligible'],
    // Specs
    ['מפרט המערכת', 'System Specs'],
    ['רכיבים Tier-1 בלבד', 'Tier-1 components only'],
    ['פאנלים', 'Panels'],
    ['אינוורטר', 'Inverter'],
    ['סוללה', 'Battery'],
    ['הספק DC', 'DC Power'],
    ['חיבור', 'Grid connection'],
    ['עיגון', 'Mounting'],
    ['ניטור', 'Monitoring'],
    ['הגנות', 'Protections'],
    ['Jinko Solar N-Type 580W (25 שנות אחריות ייצור)', 'Jinko Solar N-Type 580W (25-year product warranty)'],
    ['Huawei SUN2000-12KTL-M2 היברידי (10 שנות אחריות)', 'Huawei SUN2000-12KTL-M2 hybrid (10-year warranty)'],
    ['Huawei LUNA2000-10-S0 · 10 kWh · LFP (10 שנות אחריות · 100% DoD)', 'Huawei LUNA2000-10-S0 · 10 kWh · LFP (10-year warranty · 100% DoD)'],
    ['PEA On-Grid Hybrid · גיבוי אוטומטי בהפסקות חשמל', 'PEA On-Grid Hybrid · automatic backup during blackouts'],
    ['Tile hooks אלומיניום עם איטום EPDM', 'Aluminum tile hooks with EPDM sealing'],
    ['FusionSolar App — ייצור בזמן אמת + התראות', 'FusionSolar App — real-time production + alerts'],
    ['DC/AC isolator, SPD, RCD, mini-CB (תקן IEC 62446)', 'DC/AC isolator, SPD, RCD, mini-CB (IEC 62446 standard)'],
    // Production
    ['תחזית ייצור', 'Production Forecast'],
    ['שעות שמש חודשיות · Koh Phangan 9.7°N', 'Monthly peak sun hours · Koh Phangan 9.7°N'],
    ['חישוב עצמאי לפי נתוני קרינה NASA SSE לאזור הספציפי, עם תיקון לחום טרופי (PR=0.78).', 'Independent calculation using NASA SSE irradiance data for this location, with tropical heat correction (PR=0.78).'],
    ['ממוצע שנתי (PSH)', 'Annual Average (PSH)'],
    ['שעות / יום', 'hours / day'],
    ['ייצור צפוי שנתי', 'Annual production'],
    ['ייצור ממוצע חודשי', 'Monthly average'],
    ['ינו', 'Jan'], ['פבר', 'Feb'], ['מרץ', 'Mar'], ['אפר', 'Apr'],
    ['מאי', 'May'], ['יונ', 'Jun'], ['יול', 'Jul'], ['אוג', 'Aug'],
    ['ספט', 'Sep'], ['אוק', 'Oct'], ['נוב', 'Nov'], ['דצמ', 'Dec'],
    // Financial
    ['השקעה והחזר', 'Investment & Return'],
    ['תחזית פיננסית', 'Financial Forecast'],
    ['Turnkey — הכל כלול', 'Turnkey — all included'],
    ['מחיר קבוע · לא כולל VAT · תשלום: 50% התחלה + 50% סיום התקנה', 'Fixed price · excl. VAT · payment: 50% deposit + 50% on completion'],
    ['22 פאנלים Jinko N-Type 580W', '22× Jinko N-Type 580W panels'],
    ['Huawei SUN2000-12KTL-M2 היברידי', 'Huawei SUN2000-12KTL-M2 hybrid'],
    ['סוללת Huawei LUNA2000 10 kWh — כלולה', 'Huawei LUNA2000 10 kWh battery — included'],
    ['מבנה תומך, כבלים, הגנות IEC 62446', 'Mounting, cables, IEC 62446 protections'],
    ['התקנה מקצועית (3-4 ימי עבודה)', 'Professional installation (3-4 working days)'],
    ['לוגיסטיקה + שילוח לקופנגן', 'Logistics + shipping to Koh Phangan'],
    ['הגשה ואישור PEA', 'PEA filing & approval'],
    ['אחריות 2 שנים על התקנה', '2-year installation warranty'],
    ['מוניטורינג FusionSolar + בדיקת שנה ראשונה', 'FusionSolar monitoring + first-year inspection'],
    ['תעריף PEA ממוצע', 'Avg PEA tariff'],
    ['חיסכון חודשי', 'Monthly savings'],
    ['חיסכון שנתי', 'Annual savings'],
    ['החזר השקעה (ללא מס)', 'Payback (no tax)'],
    ['שנים', 'years'],
    ['החזר (עם ניכוי מס)', 'Payback (with tax deduction)'],
    ['חיסכון מצטבר 25 שנה', '25-year cumulative savings'],
    // Tax
    ['תמריץ ממשלת תאילנד · 2026', 'Thai Government Incentive · 2026'],
    ['ניכוי מס הכנסה עד ฿200,000', 'Income Tax Deduction up to ฿200,000'],
    ['על התקנות סולאריות Residential On-Grid עד 10 kWp, ממשלת תאילנד מעניקה', 'For residential on-grid solar installations up to 10 kWp, the Thai government offers a'],
    ['ניכוי מס הכנסה של עד ฿200,000', 'tax deduction of up to ฿200,000'],
    ['בשנת המס של ההתקנה.', 'in the installation tax year.'],
    ['בפועל, ההשקעה נטו יורדת ל-', 'In practice, net investment drops to'],
    ['~฿250,000', '~฿250,000'],
    ['והחזר ההשקעה מתקצר ל-', 'and payback shortens to'],
    ['~3.1 שנים', '~3.1 years'],
    ['ניתן לקזז עם חשבוניות רשמיות — TM Energy מספקת את כל המסמכים הנדרשים.', 'Deductible against official invoices — TM Energy provides all required documentation.'],
    // Cumulative
    ['חיסכון מצטבר', 'Cumulative Savings'],
    ['ROI לאורך זמן (אחרי ניכוי מס)', 'ROI over time (after tax deduction)'],
    ['שנה 5', 'Year 5'], ['שנה 10', 'Year 10'], ['שנה 15', 'Year 15'],
    ['שנה 20', 'Year 20'], ['שנה 25', 'Year 25'],
    // Timeline
    ['לוחות זמנים', 'Timeline'],
    ['מאישור ההצעה ועד חיבור לרשת', 'From proposal approval to grid connection'],
    ['שבוע 1', 'Week 1'],
    ['שבוע 2-3', 'Weeks 2-3'],
    ['שבוע 4', 'Week 4'],
    ['שבוע 5-6', 'Weeks 5-6'],
    ['חתימת חוזה · תשלום ראשון · הזמנת ציוד', 'Contract signing · first payment · equipment order'],
    ['הכנת מסמכי PEA · הגשה · הגעת ציוד', 'PEA documents · filing · equipment arrival'],
    ['התקנה פיזית (3 ימים) · בדיקות', 'Physical installation (3 days) · testing'],
    ['אישור PEA · החלפת מונה · COD (commissioning)', 'PEA approval · meter replacement · COD (commissioning)'],
    // CTA
    ['מוכן להתחיל לחסוך?', 'Ready to start saving?'],
    ['הזמן אותנו לביקור אתר בקופנגן — ללא עלות, ללא התחייבות.', 'Book a free, no-obligation site visit in Koh Phangan.'],
    ['WhatsApp · +66 94 669 2011', 'WhatsApp · +66 94 669 2011'],
    // Footer
    ['TM Energy · Phangan', 'TM Energy · Phangan'],
    ['הצעה זו תקפה 30 יום · REF AMIR-001 · אפריל 2026', 'This proposal is valid for 30 days · REF AMIR-001 · April 2026'],
    // Section labels (after specific heading replacements)
  ],
  th: [
    ['<html lang="he" dir="rtl">', '<html lang="th" dir="ltr">'],
    ['direction: rtl;', 'direction: ltr;'],
    ['TM Energy — הצעת מחיר סולארית · אמיר מזרחי', 'TM Energy — ใบเสนอราคาระบบโซลาร์ · Amir Mizrahi'],
    ['הצעת מחיר למערכת סולארית', 'ใบเสนอราคาระบบโซลาร์'],
    ['קופנגן, תאילנד', 'เกาะพะงัน, ประเทศไทย'],
    ['הצעת מחיר · אפריל 2026', 'ใบเสนอราคา · เมษายน 2026'],
    ['מערכת סולארית', 'ระบบโซลาร์'],
    ['12.76 kWp + סוללה', '12.76 kWp + แบตเตอรี่'],
    ['מערכת היברידית מלאה Huawei לקופנגן — 22 פאנלים Jinko N-Type + אינוורטר Huawei SUN2000 + סוללת Huawei LUNA2000 10 kWh. עצמאות אנרגטית גם בהפסקות חשמל, חיסכון של 79,900 ฿ בשנה.', 'ระบบไฮบริด Huawei สำหรับเกาะพะงัน — แผง Jinko N-Type 22 แผง + อินเวอร์เตอร์ Huawei SUN2000 + แบตเตอรี่ Huawei LUNA2000 10 kWh. พึ่งพาตนเองด้านพลังงานแม้ไฟดับ ประหยัด ฿79,900 ต่อปี'],
    ['לקוח', 'ลูกค้า'],
    ['מיקום', 'สถานที่'],
    ['Koh Phangan, TH', 'เกาะพะงัน, TH'],
    ['תוקף', 'มีอายุ'],
    ['30 יום', '30 วัน'],
    ['סימולציה ויזואלית', 'ภาพจำลอง'],
    ['איך המערכת תיראה על הגג שלך', 'ระบบบนหลังคาของคุณจะเป็นแบบนี้'],
    ['דימוי AI מדויק המבוסס על תמונת הרחפן של הגג — מראה מדויק של מיקום ומספר הפאנלים.', 'ภาพจำลองโดย AI อิงจากภาพโดรน — ตำแหน่งและจำนวนแผงที่แม่นยำ'],
    ['לפני', 'ก่อน'],
    ['אחרי', 'หลัง'],
    ['תמונת רחפן', 'ภาพโดรน'],
    ['22 פאנלים · 12.76 kWp', '22 แผง · 12.76 kWp'],
    ['ניתוח הגג', 'วิเคราะห์หลังคา'],
    ['מדידות ותכנון', 'ขนาดและแผนผัง'],
    ['m² שטח גג', 'ตรม. พื้นที่หลังคา'],
    ['פאנלים פעילים', 'แผงที่ใช้งาน'],
    ['אוריינטציה', 'ทิศทาง'],
    ['ציר N-S', 'แกน N-S'],
    ['סוג גג', 'ประเภทหลังคา'],
    ['רעפים', 'กระเบื้อง'],
    ['מדרון שמאל (מזרח)', 'ด้านซ้าย (ตะวันออก)'],
    ['מדרון ימין (מערב)', 'ด้านขวา (ตะวันตก)'],
    ['חלק עליון (clerestory)', 'ส่วนบน (clerestory)'],
    ['סה״כ פאנלים', 'รวมแผงทั้งหมด'],
    ['הצללה צפויה', 'การบังเงา'],
    ['פאנלים (2×5)', 'แผง (2×5)'],
    ['פאנלים (2×4)', 'แผง (2×4)'],
    ['פאנלים נוספים (2×2)', 'แผงเพิ่ม (2×2)'],
    ['5-8% בבוקר מעץ המנגו · זניח', '5-8% ตอนเช้าจากต้นมะม่วง · น้อยมาก'],
    ['מפרט המערכת', 'สเปคระบบ'],
    ['רכיבים Tier-1 בלבד', 'อุปกรณ์ Tier-1 เท่านั้น'],
    ['פאנלים', 'แผง'],
    ['אינוורטר', 'อินเวอร์เตอร์'],
    ['סוללה', 'แบตเตอรี่'],
    ['הספק DC', 'กำลัง DC'],
    ['חיבור', 'การเชื่อมต่อ'],
    ['עיגון', 'โครงยึด'],
    ['ניטור', 'มอนิเตอร์'],
    ['הגנות', 'ระบบป้องกัน'],
    ['Jinko Solar N-Type 580W (25 שנות אחריות ייצור)', 'Jinko Solar N-Type 580W (รับประกันสินค้า 25 ปี)'],
    ['Huawei SUN2000-12KTL-M2 היברידי (10 שנות אחריות)', 'Huawei SUN2000-12KTL-M2 ไฮบริด (รับประกัน 10 ปี)'],
    ['Huawei LUNA2000-10-S0 · 10 kWh · LFP (10 שנות אחריות · 100% DoD)', 'Huawei LUNA2000-10-S0 · 10 kWh · LFP (รับประกัน 10 ปี · DoD 100%)'],
    ['PEA On-Grid Hybrid · גיבוי אוטומטי בהפסקות חשמל', 'PEA On-Grid Hybrid · สำรองไฟอัตโนมัติเมื่อไฟดับ'],
    ['Tile hooks אלומיניום עם איטום EPDM', 'Tile hooks อลูมิเนียมกันซึม EPDM'],
    ['FusionSolar App — ייצור בזמן אמת + התראות', 'FusionSolar App — ผลผลิตเรียลไทม์ + แจ้งเตือน'],
    ['DC/AC isolator, SPD, RCD, mini-CB (תקן IEC 62446)', 'DC/AC isolator, SPD, RCD, mini-CB (มาตรฐาน IEC 62446)'],
    ['תחזית ייצור', 'คาดการณ์ผลผลิต'],
    ['שעות שמש חודשיות · Koh Phangan 9.7°N', 'Peak sun hours รายเดือน · เกาะพะงัน 9.7°N'],
    ['חישוב עצמאי לפי נתוני קרינה NASA SSE לאזור הספציפי, עם תיקון לחום טרופי (PR=0.78).', 'คำนวณจากข้อมูล NASA SSE ของพื้นที่นี้ ปรับแก้ความร้อนเขตร้อน (PR=0.78)'],
    ['ממוצע שנתי (PSH)', 'เฉลี่ยต่อปี (PSH)'],
    ['שעות / יום', 'ชม. / วัน'],
    ['ייצור צפוי שנתי', 'ผลผลิตต่อปี'],
    ['ייצור ממוצע חודשי', 'เฉลี่ยต่อเดือน'],
    ['ינו', 'ม.ค.'], ['פבר', 'ก.พ.'], ['מרץ', 'มี.ค.'], ['אפר', 'เม.ย.'],
    ['מאי', 'พ.ค.'], ['יונ', 'มิ.ย.'], ['יול', 'ก.ค.'], ['אוג', 'ส.ค.'],
    ['ספט', 'ก.ย.'], ['אוק', 'ต.ค.'], ['נוב', 'พ.ย.'], ['דצמ', 'ธ.ค.'],
    ['השקעה והחזר', 'การลงทุนและผลตอบแทน'],
    ['תחזית פיננסית', 'คาดการณ์ทางการเงิน'],
    ['Turnkey — הכל כלול', 'Turnkey — รวมทุกอย่าง'],
    ['מחיר קבוע · לא כולל VAT · תשלום: 50% התחלה + 50% סיום התקנה', 'ราคาคงที่ · ไม่รวม VAT · จ่าย 50% มัดจำ + 50% ติดตั้งเสร็จ'],
    ['22 פאנלים Jinko N-Type 580W', 'แผง Jinko N-Type 580W จำนวน 22 แผง'],
    ['Huawei SUN2000-12KTL-M2 היברידי', 'Huawei SUN2000-12KTL-M2 ไฮบริด'],
    ['סוללת Huawei LUNA2000 10 kWh — כלולה', 'แบตเตอรี่ Huawei LUNA2000 10 kWh — รวมแล้ว'],
    ['מבנה תומך, כבלים, הגנות IEC 62446', 'โครงยึด สายไฟ ระบบป้องกัน IEC 62446'],
    ['התקנה מקצועית (3-4 ימי עבודה)', 'ติดตั้งโดยมืออาชีพ (3-4 วัน)'],
    ['לוגיסטיקה + שילוח לקופנגן', 'ขนส่ง + จัดส่งถึงเกาะพะงัน'],
    ['הגשה ואישור PEA', 'ยื่นและอนุมัติ PEA'],
    ['אחריות 2 שנים על התקנה', 'รับประกันการติดตั้ง 2 ปี'],
    ['מוניטורינג FusionSolar + בדיקת שנה ראשונה', 'มอนิเตอร์ FusionSolar + ตรวจสอบปีแรก'],
    ['תעריף PEA ממוצע', 'อัตราค่าไฟ PEA เฉลี่ย'],
    ['חיסכון חודשי', 'ประหยัดต่อเดือน'],
    ['חיסכון שנתי', 'ประหยัดต่อปี'],
    ['החזר השקעה (ללא מס)', 'คืนทุน (ไม่รวมลดภาษี)'],
    ['שנים', 'ปี'],
    ['החזר (עם ניכוי מס)', 'คืนทุน (รวมลดภาษี)'],
    ['חיסכון מצטבר 25 שנה', 'ประหยัดสะสม 25 ปี'],
    ['תמריץ ממשלת תאילנד · 2026', 'มาตรการรัฐบาลไทย · 2026'],
    ['ניכוי מס הכנסה עד ฿200,000', 'ลดหย่อนภาษีเงินได้สูงสุด ฿200,000'],
    ['על התקנות סולאריות Residential On-Grid עד 10 kWp, ממשלת תאילנד מעניקה', 'สำหรับระบบโซลาร์ On-Grid บ้านพักอาศัยถึง 10 kWp รัฐบาลให้'],
    ['ניכוי מס הכנסה של עד ฿200,000', 'ลดหย่อนภาษีเงินได้สูงสุด ฿200,000'],
    ['בשנת המס של ההתקנה.', 'ในปีภาษีที่ติดตั้ง'],
    ['בפועל, ההשקעה נטו יורדת ל-', 'ในทางปฏิบัติ การลงทุนสุทธิจะเหลือ'],
    ['והחזר ההשקעה מתקצר ל-', 'และระยะคืนทุนจะสั้นลงเหลือ'],
    ['~3.1 שנים', '~3.1 ปี'],
    ['ניתן לקזז עם חשבוניות רשמיות — TM Energy מספקת את כל המסמכים הנדרשים.', 'ใช้หักภาษีได้กับใบกำกับภาษีอย่างเป็นทางการ — TM Energy จัดเตรียมเอกสารทั้งหมด'],
    ['חיסכון מצטבר', 'ประหยัดสะสม'],
    ['ROI לאורך זמן (אחרי ניכוי מס)', 'ROI ตามเวลา (หลังลดหย่อนภาษี)'],
    ['שנה 5', 'ปีที่ 5'], ['שנה 10', 'ปีที่ 10'], ['שנה 15', 'ปีที่ 15'],
    ['שנה 20', 'ปีที่ 20'], ['שנה 25', 'ปีที่ 25'],
    ['לוחות זמנים', 'ตารางเวลา'],
    ['מאישור ההצעה ועד חיבור לרשת', 'จากอนุมัติใบเสนอจนเชื่อมต่อโครงข่าย'],
    ['שבוע 1', 'สัปดาห์ที่ 1'],
    ['שבוע 2-3', 'สัปดาห์ที่ 2-3'],
    ['שבוע 4', 'สัปดาห์ที่ 4'],
    ['שבוע 5-6', 'สัปดาห์ที่ 5-6'],
    ['חתימת חוזה · תשלום ראשון · הזמנת ציוד', 'ลงนามสัญญา · จ่ายงวดแรก · สั่งอุปกรณ์'],
    ['הכנת מסמכי PEA · הגשה · הגעת ציוד', 'เตรียมเอกสาร PEA · ยื่น · อุปกรณ์มาถึง'],
    ['התקנה פיזית (3 ימים) · בדיקות', 'ติดตั้ง (3 วัน) · ทดสอบ'],
    ['אישור PEA · החלפת מונה · COD (commissioning)', 'อนุมัติ PEA · เปลี่ยนมิเตอร์ · COD'],
    ['מוכן להתחיל לחסוך?', 'พร้อมประหยัดแล้วหรือยัง?'],
    ['הזמן אותנו לביקור אתר בקופנגן — ללא עלות, ללא התחייבות.', 'นัดเราเข้าสำรวจพื้นที่ที่เกาะพะงัน — ฟรี ไม่มีข้อผูกมัด'],
    ['הצעה זו תקפה 30 יום · REF AMIR-001 · אפריל 2026', 'ใบเสนอนี้มีอายุ 30 วัน · REF AMIR-001 · เมษายน 2026'],
  ],
}

function translate(src, dictionary) {
  let out = src
  for (const [he, other] of dictionary) {
    out = out.split(he).join(other)
  }
  return out
}

const en = translate(src, dict.en)
writeFileSync(join(__dirname, 'template-en.html'), en)
console.log(`✅ template-en.html (${en.length} chars)`)

const th = translate(src, dict.th)
writeFileSync(join(__dirname, 'template-th.html'), th)
console.log(`✅ template-th.html (${th.length} chars)`)
